=== olgaBovkaniuk/test/out/production/control_work_2/controlWork2/task3/PurchaseOrder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="PuurchaseOrder" type="PuurchaseOrderType"/>
  <xs:complexType name="PuurchaseOrderType">
    <xs:sequence>
      <xs:element name="Item" type="ItemType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="OrderDate" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="ItemType">
    <xs:sequence>
      <xs:element name="ProductName" type="xs:string"/>
      <xs:element name="Quantity" type="xs:string"/>
      <xs:element name="USPrice" type="xs:string"/>
      <xs:element type="xs:string" name="Comment" minOccurs="0"/>
      <xs:element type="xs:string" name="ShipDate" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="PartNumber" type="xs:string" use="optional"/>
  </xs:complexType>
</xs:schema>

=== olgaBovkaniuk/test/out/production/control_work_2/controlWork2/task3/PurchaseOrder.xml
<?xml version="1.0" encoding="UTF-8" ?>
<PuurchaseOrder OrderDate="1999-10-20"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="src/controlWork2/task3/PurchaseOrder.xsd PurchaseOrder.xsd">
    <Item PartNumber="872-AA">
        <ProductName>Lawnmower</ProductName>
        <Quantity>1</Quantity>
        <USPrice>148,95</USPrice>
        <Comment>Confirm this is electric</Comment>
    </Item>
    <Item PartNumber="926-AA">
        <ProductName>Baby Monitor</ProductName>
        <Quantity>2</Quantity>
        <USPrice>39,98</USPrice>
        <ShipDate>1999-05-21</ShipDate>
    </Item>
</PuurchaseOrder>
